# values.yaml
global:
  licenseplate: 6e2f55
  environment: dev
  vault:
    role: ""
    subPath: ""
    podAnnotations:
      vault.hashicorp.com/auth-path: "auth/k8s-silver"
      vault.hashicorp.com/namespace: "platform-services"
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-token: "false"
      vault.hashicorp.com/agent-pre-populate: "true"
      vault.hashicorp.com/agent-pre-populate-only: "true"
      vault.hashicorp.com/agent-requests-cpu: "50m"
      vault.hashicorp.com/agent-limits-cpu: "100m"
      vault.hashicorp.com/agent-requests-mem: "32Mi"
      vault.hashicorp.com/agent-limits-mem: "64Mi"
  env:
    "Env": ""
    "SECURE_HEADERS": "true"
    "AUTH_TRUST_HOST": "true"
  serviceAccountName: 6e2f55-vault

# Configuration for the TypeScript application
apiImage:
  repository: image-registry.openshift-image-registry.svc:5000/6e2f55-dev/rockychat-api
  tag: ""
  pullPolicy: IfNotPresent
  # Add any other configuration specific to your TypeScript application

replicaCount:
  api: 1
  redis: 1

resources:
  api:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 128Mi
  redis:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
      
  # OpenShift resources
buildConfig:
  enabled: true
  strategy: Source
  source:
    type: Git
    git:
      uri: "https://github.com/your-repo/your-app"
      ref: "main"
imageStream:
  enabled: true

    # Add any other deployment configuration

service:
  api:
    type: ClusterIP
    port: 3000
  redis:
    type: ClusterIP
    port: 6379
  route:
    enabled: true
    hostname: my-typescript-app.example.com
    path: /

  # Add any other OpenShift resources needed for your application

# Configuration for Redis
redis:
  enabled: true
  replica:
    replicaCount: 3
  # image: redis
  # tag: 7.2.4
  # pullPolicy: IfNotPresent
  # port: 6379
  # storage:
  #   size: 200Mi

  auth:
    existingSecret: rockychat-devops-redis-secret
    existingSecretPasswordKey: redis-password
sentinel:
  resources:
    limits:
      cpu: 1
      memory: 1500Mi
    requests:
      cpu: 0.5
      memory: 500Mi
master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: netapp-file-standard
replica:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: netapp-file-standard


networkPolicy:
  intraNamespace:
    enabled: true
  allowFromIngress:
    enabled: true
