version: '3.8'

services:
  # chatbot:
  rockychat:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - rockychat-redis
  # Redis DB:
  rockychat-redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    env_file:
      - .env
    # volumes:
