version: '3.8'
services:
  rockychat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
    ports:
      - '3000:3000'
    # volumes:
    #   - .:/src
    env_file:
      - .env
    depends_on:
      - rockychat-redis
  rockychat-redis:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    env_file:
      - .env
