apiVersion: v1
kind: Service
metadata:
  name: {{ include "rockychat.fullname" . }}-api
  labels:
    {{- include "rockychat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "rockychat.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
