---
apiVersion: v1
kind: ImageStream
metadata:
  name: nodejs-20
  namespace: {{ project_name }}
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: ImageStreamTag
      name: nodejs:10
      namespace: openshift
    importPolicy: {}
    name: "1"
    referencePolicy:
      type: Local
