apiVersion: v1
kind: Service
metadata:
  name: {{ include "rockychat.fullname" . }}-redis
  namespace: {{ .Values.global.licenseplate }}-{{ .Values.global.environment }}
  labels:
    {{- include "rockychat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: master