{{- $namespace := printf "%s-%s" .Values.global.licenseplate .Values.global.environment }}
{{- $secretName := "rockychat-devops-redis-secret" }}
{{- $secretExists := lookup "v1" "Secret" $namespace $secretName }}
{{- if not $secretExists }}
apiVersion: v1
kind: Secret
metadata:
  name: rockychat-devops-redis-secret
  namespace: {{ .Values.global.licenseplate }}-{{ .Values.global.environment }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  redis-password: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}